##DaedalusMod Main Configuration File
##If you have any questions on this configuration file, please contact Wild1145

admininfo:
    title: '&bHow to apply for admin on the TotalFreedom Server:'
    line1: '&6Do not ask for admin in game'
    line2: '&2Be helpful within the server'
    line3: '&6Report those breaking the rules'
    line4: '&2And apply on our forums at the link: &9www.totalfreedom.boards.net'
    line5: This is line 5
    line6: This is line 6
    
aienable:
    title: true
    line1: true
    line2: true
    line3: true
    line4: true
    line5: false
    line6: false